### ISSUE TITLE
Players are not affected by agents after respawn

### ISSUE THREAD

**Issue by Wulfle** [assaultboy/ChemicalWarfare#1]

**Comment by kamkill01011** [comment]
The problem is that when you respawn the PFH is removed, but the value of "CBRN_chemicalDamageHandler" is not reset to -1. I'm not good at SQF programint but here is a workaround (place it in any respawnable unit): 

`this addEventHandler ["Respawn", { 
    params ["_unit", "_corpse"]; 
    _unit setVariable ["CBRN_chemicalDamageHandler", -1];
}];`
