### ISSUE TITLE
Option to disable the faction gear option

### ISSUE THREAD

**Issue by ASO-TheM** [assaultboy/ChemicalWarfare#19]
I would like to see an option to disable the faction gear option in my addon options

**Comment by assaultboy** [comment]
I don't understand what you mean?
Do you mean disable factions from receiving masks automatically? If so you can just leave the faction to none which is the default.

**Comment by ASO-TheM** [comment]
Yesterday I checked out the options and my mask was gone when I chose the none option. Today it didn't happen. Maybe it was something else
