### ISSUE TITLE
Wiki Spawning Gas parameters

### ISSUE THREAD

**Issue by kamkill01011** [assaultboy/ChemicalWarfare#24]
In the `Wiki`, in page for `Chemical Types`, in the `Spawning Gas` section, the `Lifetime` parameter is missing. [https://github.com/assaultboy/ChemicalWarfare/wiki/Chemical-Types#spawning-gas](https://github.com/assaultboy/ChemicalWarfare/wiki/Chemical-Types#spawning-gas)

**Comment by assaultboy** [comment]
Fixed, thank you
