### ISSUE TITLE
Forcing gas-mask on person

### ISSUE THREAD

**Issue by Bergfinn** [assaultboy/ChemicalWarfare#25]
Can you make it so that the gas mask is ACE-Interactable so you can put a gasmask on an unconscious player. For Medics that would be a nice-to-have. In order to save a person while under gas attack. 

Cheers!

**Comment by assaultboy** [comment]
This is already a feature. Use ACE interact with the head of an unconscious player with a mask in either their inventory or yours to place the mask on them.
